@echo off
echo Starting Attendance System...

echo Starting Backend Server...
start "Backend Server" /D "backend" npm run dev

echo Starting Frontend Application...
start "Frontend Application" /D "frontend" npm run dev

echo Starting AI/ML Service...
start "AI Service" /D "ai_ml" python app.py

echo All services starting...
