const nodemailer = require('nodemailer');
const dotenv = require('dotenv');

dotenv.config();

/**
 * Email service for sending notifications
 */
class EmailService {
  constructor() {
    this.transporter = nodemailer.createTransporter({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: process.env.SMTP_PORT || 587,
      secure: false, // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    this.from = process.env.EMAIL_FROM || '"Attendance System" <no-reply@attendancesystem.com>';
  }

  /**
   * Send email
   * @param {Object} options 
   * @param {string} options.to - Recipient email
   * @param {string} options.subject - Email subject
   * @param {string} options.text - Plain text content
   * @param {string} options.html - HTML content
   * @returns {Promise<Object>}
   */
  async sendEmail(options) {
    try {
      const mailOptions = {
        from: this.from,
        to: options.to,
        subject: options.subject,
        text: options.text,
        html: options.html,
      };

      const info = await this.transporter.sendMail(mailOptions);
      console.log('Email sent: %s', info.messageId);
      return { success: true, messageId: info.messageId };
    } catch (error) {
      console.error('Error sending email:', error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Send attendance report email
   * @param {Object} data 
   * @returns {Promise<Object>}
   */
  async sendAttendanceReport(data) {
    const { recipient, date, className, summary } = data;

    const subject = `Attendance Report - ${className} - ${date}`;

    const text = `
Attendance Report for ${className} on ${date}

Total Students: ${summary.total}
Present: ${summary.present}
Absent: ${summary.absent}
Late: ${summary.late}
Leave: ${summary.leave}

Attendance Percentage: ${summary.percentage}%

Generated by Attendance System
    `;

    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>Attendance Report</h2>
        <p><strong>Class:</strong> ${className}</p>
        <p><strong>Date:</strong> ${date}</p>
        
        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
          <tr style="background-color: #f2f2f2;">
            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Metric</th>
            <th style="border: 1px solid #ddd; padding: 8px; text-align: right;">Count</th>
          </tr>
          <tr>
            <td style="border: 1px solid #ddd; padding: 8px;">Total Students</td>
            <td style="border: 1px solid #ddd; padding: 8px; text-align: right;">${summary.total}</td>
          </tr>
          <tr>
            <td style="border: 1px solid #ddd; padding: 8px;">Present</td>
            <td style="border: 1px solid #ddd; padding: 8px; text-align: right;">${summary.present}</td>
          </tr>
          <tr>
            <td style="border: 1px solid #ddd; padding: 8px;">Absent</td>
            <td style="border: 1px solid #ddd; padding: 8px; text-align: right;">${summary.absent}</td>
          </tr>
          <tr>
            <td style="border: 1px solid #ddd; padding: 8px;">Late</td>
            <td style="border: 1px solid #ddd; padding: 8px; text-align: right;">${summary.late}</td>
          </tr>
          <tr>
            <td style="border: 1px solid #ddd; padding: 8px;">Leave</td>
            <td style="border: 1px solid #ddd; padding: 8px; text-align: right;">${summary.leave}</td>
          </tr>
        </table>
        
        <p><strong>Attendance Percentage:</strong> ${summary.percentage}%</p>
        
        <hr>
        <p style="color: #666; font-size: 12px;">
          Generated by Attendance System
        </p>
      </div>
    `;

    return await this.sendEmail({
      to: recipient,
      subject,
      text,
      html,
    });
  }

  /**
   * Send offline sync report
   * @param {Object} data 
   * @returns {Promise<Object>}
   */
  async sendSyncReport(data) {
    const { recipient, results } = data;

    const subject = 'Offline Sync Report';

    const text = `
Offline Sync Report

Successfully synced: ${results.synced}
Failed to sync: ${results.failed}

Details:
${results.details.map(detail => 
  `- ${detail.recordId}: ${detail.status}${detail.reason ? ` (${detail.reason})` : ''}`
).join('\n')}

Generated by Attendance System
    `;

    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>Offline Sync Report</h2>
        
        <div style="background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 20px 0;">
          <h3>Summary</h3>
          <p><strong>Successfully synced:</strong> ${results.synced}</p>
          <p><strong>Failed to sync:</strong> ${results.failed}</p>
        </div>
        
        <h3>Details</h3>
        <ul>
          ${results.details.map(detail => 
            `<li>${detail.recordId}: ${detail.status}${detail.reason ? ` <em>(${detail.reason})</em>` : ''}</li>`
          ).join('')}
        </ul>
        
        <hr>
        <p style="color: #666; font-size: 12px;">
          Generated by Attendance System
        </p>
      </div>
    `;

    return await this.sendEmail({
      to: recipient,
      subject,
      text,
      html,
    });
  }

  /**
   * Send password reset email
   * @param {Object} data 
   * @returns {Promise<Object>}
   */
  async sendPasswordReset(data) {
    const { recipient, resetToken, userName } = data;

    const resetUrl = `${process.env.FRONTEND_URL}/reset-password?token=${resetToken}`;

    const subject = 'Password Reset Request';

    const text = `
Hello ${userName},

You requested a password reset. Click the link below to reset your password:

${resetUrl}

If you didn't request this, please ignore this email.

This link will expire in 1 hour.

Generated by Attendance System
    `;

    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>Password Reset Request</h2>
        <p>Hello <strong>${userName}</strong>,</p>
        
        <p>You requested a password reset. Click the button below to reset your password:</p>
        
        <div style="text-align: center; margin: 30px 0;">
          <a href="${resetUrl}" 
             style="background-color: #007bff; color: white; padding: 12px 24px; 
                    text-decoration: none; border-radius: 5px; display: inline-block;">
            Reset Password
          </a>
        </div>
        
        <p>If you didn't request this, please ignore this email.</p>
        
        <p><small>This link will expire in 1 hour.</small></p>
        
        <hr>
        <p style="color: #666; font-size: 12px;">
          Generated by Attendance System
        </p>
      </div>
    `;

    return await this.sendEmail({
      to: recipient,
      subject,
      text,
      html,
    });
  }

  /**
   * Send welcome email
   * @param {Object} data 
   * @returns {Promise<Object>}
   */
  async sendWelcomeEmail(data) {
    const { recipient, userName, schoolName } = data;

    const subject = 'Welcome to Attendance System';

    const text = `
Welcome ${userName}!

You have been registered to the Attendance System for ${schoolName}.

You can now log in using your email and the password provided by your administrator.

Login URL: ${process.env.FRONTEND_URL}/login

Generated by Attendance System
    `;

    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>Welcome to Attendance System!</h2>
        <p>Hello <strong>${userName}</strong>,</p>
        
        <p>You have been registered to the Attendance System for <strong>${schoolName}</strong>.</p>
        
        <p>You can now log in using your email and the password provided by your administrator.</p>
        
        <div style="text-align: center; margin: 30px 0;">
          <a href="${process.env.FRONTEND_URL}/login" 
             style="background-color: #28a745; color: white; padding: 12px 24px; 
                    text-decoration: none; border-radius: 5px; display: inline-block;">
            Login to System
          </a>
        </div>
        
        <hr>
        <p style="color: #666; font-size: 12px;">
          Generated by Attendance System
        </p>
      </div>
    `;

    return await this.sendEmail({
      to: recipient,
      subject,
      text,
      html,
    });
  }
}

module.exports = new EmailService();